---
- name: "Check for Latest Oxide"
  ansible.builtin.script: "{{ playbook_dir }}/python_helpers/getmods.py"
    args:
      executable: python3
- name: Check for updated Oxide file
  stat:
    path: "{{ download.local }}"
  register: stat_result
  when: download.update
- name: Unarchive oxide file
  ansible.builtin.unarchive:
    src: "{{ download.local }}"
    dest: "{{ server.directory }}/"
  when: download.update and stat_result.stat.exists
- name: Remove oxide file
  ansible.builtin.file:
    path: "{{ download.local }}"
    state: absent
- name: Get RustEdit
  get_url:
    url: "https://github.com/k1lly0u/Oxide.Ext.RustEdit/archive/refs/tags/{{ RustEditdll.versionfile }}"
    dest: "{{ server.directory }}/RustDedicated_Data/Managed"
- name: Extract RustEdit
  ansible.builtin.unarchive:
    src: "{{ server.directory }}/RustDedicated_Data/Managed/{{ RustEditdll.versionfile }}"
    dest: "{{ server.directory }}/RustDedicated_Data/Managed"
- name: Get RustIO
  uri:
    url: "http://playrust.io/latest/oxide"
    dest: "{{ server.directory }}/RustDedicated_Data/Managed"
    follow_redirects: yes
